[project]
name = "chatroom-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask-appbuilder>=4.8.0",
    "flask-cors>=6.0.1",
    "flask-socketio>=5.5.1",
    "pyjwt>=2.10.1",
    "python-dotenv>=1.1.1",
]
